version: '3.5'
services:
  frontend:
    image: richwalkman/apsifront:BUILD_BUILDID
    volumes:
      - static:/static
    ports:
      - "80:80"

  backend:
    image: richwalkman/apsibackend:BUILD_BUILDID
    expose:
      - 8000
    command: gunicorn apsi_backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - backend/apsi_backend/.env.prod
    volumes:
      - static:/static
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/apsi_backend/.env.prod.db

volumes:
  postgres_data:
  static: